### PR TITLE
Override docker image in the linter task

### PR DESCRIPTION
**Pull request by willdurand**

### CODE REVIEW

**Comment by willdurand** [comment]
Looks like this is working as intended, see: https://firefox-ci-tc.services.mozilla.com/tasks/NQxKxnWdTc6LZs6rp_HjoQ, which is based on https://github.com/mozilla-extensions/privileged-test-xpi/compare/test-xpi-template

**Comment by willdurand** [comment]
@wagnerand or @jcristau r?

**Comment by wagnerand** [comment]
I'd pass on this one as I am not familiar enough with the issue, this solution or the impact of either to give this a meaningful review.

**Review by jcristau — COMMENTED** [review]
I'm not familiar with the addons linter but I'm surprised it would have to run with the same image as the build.  Isn't what we need to do here just to change the linter image to have a newer node, and always use that?

**Comment by willdurand** [comment]
> I'm not familiar with the addons linter but I'm surprised it would have to run with the same image as the build. Isn't what we need to do here just to change the linter image to have a newer node, and always use that?

There is a feature that allows to override the node version from the project's repo. That's what I am backporting here. Both `build` and `test` tasks are supporting this already.

**Comment by jcristau** [comment]
> > I'm not familiar with the addons linter but I'm surprised it would have to run with the same image as the build. Isn't what we need to do here just to change the linter image to have a newer node, and always use that?
> 
> There is a feature that allows to override the node version from the project's repo. That's what I am backporting here. Both `build` and `test` tasks are supporting this already.

I understand that for build and test.  But why is that necessary for the linter?  Is the linter running code from the project?

**Comment by willdurand** [comment]
> I understand that for build and test. But why is that necessary for the linter? Is the linter running code from the project?

It isn't but I thought it'd be useful for consistency and for temporarily fixing issues like the one we're facing with Node 16. That said, I am not too attached to that PR so either approve or close it :)

**Comment by jcristau** [comment]
Thanks, I'm going to go with #44 instead which should also fix this.

**Pull request closed without merging**
