### PR TITLE
Pass --privileged option to addons-linter

### LINKED ISSUE #33: Pass `--privileged` flag to addons-linter
A new CLI flag is going to be added to addons-linter in order to enable special checks for privileged extensions (see: https://github.com/mozilla/addons-linter/issues/4324). This flag will eventually enforce the linted XPIs to be privileged extensions, which should be the case for all the extensions that use this template.

The idea is to pass this flag _now_ so that nothing will break when we'll land the actual changes (because omitting this flag will emit errors if the extension is privileged).

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla-extensions/xpi-template/issues/33

### CODE REVIEW

**Comment by willdurand** [comment]
cc @escapewindow (not urgent but I cannot request a review from you)

**Review by escapewindow — COMMENTED** [review]
Do we want to pass `--privileged` even if it's not a `privileged` addon?
(We also support normandy-privileged, mozillaonline-privileged, and system addons.)

**Comment by willdurand** [comment]
> Do we want to pass `--privileged` even if it's not a `privileged` addon? (We also support normandy-privileged, mozillaonline-privileged, and system addons.)

Ha yeah, you're probably right. I've seen those other types but didn't really think too much :/   Given that I am not sure who is who, I would suggest that we skip the linter kind for non-privileged add-ons, WDYT?

**Comment by escapewindow** [comment]
> > Do we want to pass `--privileged` even if it's not a `privileged` addon? (We also support normandy-privileged, mozillaonline-privileged, and system addons.)
> 
> Ha yeah, you're probably right. I've seen those other types but didn't really think too much :/ Given that I am not sure who is who, I would suggest that we skip the linter kind for non-privileged add-ons, WDYT?

That makes sense.
We could accomplish that in xpi-template by looking at `os.environ.get("XPI_SIGNING_TYPE")` and comparing against `privileged`. If we put that in https://github.com/mozilla-extensions/xpi-template/blob/main/taskcluster/xpi_taskgraph/linter.py#L22, that could be

```python
@transforms.add
def run_addons_linter(config, tasks):
    for task in tasks:
        if os.environ.get("XPI_SIGNING_TYPE") != "privileged":
            continue
        ...
```

We may want something similar in https://github.com/mozilla-extensions/xpi-manifest/pull/166 to only add the linter for `privileged` addons.

**Review by escapewindow — APPROVED** [review]

**Pull request merged**
